# fly.toml app configuration file generated for open-source-mlops-e2e-withered-frog-9837 on 2023-11-26T20:24:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "open-source-mlops-e2e-withered-frog-9837"
primary_region = "yul"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
