base:
  project: bank_customer_churn
  raw_data_dir: data/raw
  countries:
    - France
    - Spain
  feat_cols:
    - CreditScore
    - Age
    - Tenure
    - Balance
    - NumOfProducts
    - HasCrCard
    - IsActiveMember
    - EstimatedSalary
  targ_col: Exited
  random_state: 42

data_split:
  test_size: 0.25
  processed_data_dir: data/processed

train:
  model_type: randomforest
  model_dir: models
  model_path: models/clf-model.joblib
  params:
    n_estimators: 200
    max_depth: 20
